apiVersion: v1
kind: Service
metadata:
  name: {{ include "client.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "client.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "client.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client 