---
- name: Deploy App Stack
  hosts: ec2
  become: true

  vars:
    project_dir: /home/ubuntu/app
    image_tag: "{{ lookup('env','IMAGE_TAG') }}"
    open_webui_api_key_chat: "{{ lookup('env','OPEN_WEBUI_API_KEY_CHAT') }}"
    open_webui_api_key_gen: "{{ lookup('env','OPEN_WEBUI_API_KEY_GEN') }}"
    langsmith_api_key: "{{ lookup('env','LANGSMITH_API_KEY') }}"

  tasks:
    - name: Ensure project directory exists
      file:
        path: "{{ project_dir }}"
        state: directory

    - name: Template compose with image tags
      template:
        src: ../../docker-compose.yml.j2
        dest: "{{ project_dir }}/docker-compose.yml"

    - name: Copy Traefik configuration files
      copy:
        src: ../../traefik/
        dest: "{{ project_dir }}/traefik/"

    - name: Create acme.json file for Let's Encrypt certificates
      file:
        path: "{{ project_dir }}/traefik/acme.json"
        state: touch
        mode: '0600'
        owner: root
        group: root

    - name: Log in to GHCR
      shell: |
        echo "{{ lookup('env','GITHUB_TOKEN') }}" | docker login ghcr.io -u "{{ lookup('env','GITHUB_ACTOR') }}" --password-stdin

    - name: Pull latest images
      shell: docker-compose pull
      args:
        chdir: "{{ project_dir }}"

    - name: Run stack
      shell: docker-compose up -d
      args:
        chdir: "{{ project_dir }}"
