version: '3.8'

services:
  postgres-dev:
    image: postgres:15
    container_name: studymate-postgres-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: studymate
      POSTGRES_USER: studymate_user
      POSTGRES_PASSWORD: studymate_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      # Optional: Initialize with custom SQL
      - ./server/src/main/resources/database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
    networks:
      - dev-network

  # Add your other development services here if needed
  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres-dev
  #   networks:
  #     - dev-network

volumes:
  postgres_dev_data:

networks:
  dev-network:
    driver: bridge 