version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8082
        NODE_ENV: development
    container_name: studymate-client-dev
    restart: unless-stopped
    ports:
      - "3000:80"  # React app served via nginx
    networks:
      - dev-network
    depends_on:
      - auth-service
      - document-service
      - ai-service

  auth-service:
    build:
      context: ./microservices/auth-service
      dockerfile: Dockerfile
    container_name: studymate-auth-service-dev
    restart: unless-stopped
    ports:
      - "8081:8081"  # Auth Service API
    networks:
      - dev-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/studymate_auth
      - SPRING_DATASOURCE_USERNAME=studymate_user
      - SPRING_DATASOURCE_PASSWORD=studymate_password
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=your-super-secret-jwt-key-for-development-only-change-in-production
    depends_on:
      - postgres

  document-service:
    build:
      context: ./microservices/document-service
      dockerfile: Dockerfile
    container_name: studymate-document-service-dev
    restart: unless-stopped
    ports:
      - "8082:8082"  # Document Service API
    networks:
      - dev-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/studymate_documents
      - SPRING_DATASOURCE_USERNAME=studymate_user
      - SPRING_DATASOURCE_PASSWORD=studymate_password
      - SPRING_PROFILES_ACTIVE=dev
      - AI_SERVICE_URL=http://ai-service:8083
    depends_on:
      - postgres
      - ai-service

  ai-service:
    build:
      context: ./microservices/ai-service
      dockerfile: Dockerfile
    container_name: studymate-ai-service-dev
    restart: unless-stopped
    ports:
      - "8083:8083"  # AI Service API
    networks:
      - dev-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/studymate_ai
      - SPRING_DATASOURCE_USERNAME=studymate_user
      - SPRING_DATASOURCE_PASSWORD=studymate_password
      - SPRING_PROFILES_ACTIVE=dev
      - DOCUMENT_SERVICE_URL=http://document-service:8082
      - AI_OPENAI_API_KEY=your-openai-api-key-here
    depends_on:
      - postgres
      - weaviate

  genai:
    build:
      context: ./genAi
      dockerfile: Dockerfile
    container_name: studymate-genai-dev
    restart: unless-stopped
    ports:
      - "8085:8081"  # FastAPI GenAI service (external:internal)
    networks:
      - dev-network
    environment:
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8084
      - PYTHONPATH=/app
    depends_on:
      - weaviate
    volumes:
      - ./genAi/documents:/app/documents  # Mount documents for development

  postgres:
    image: postgres:15
    container_name: studymate-postgres-dev
    restart: unless-stopped
    ports:
      - "5432:5432"  # PostgreSQL database
    environment:
      POSTGRES_DB: studymate
      POSTGRES_USER: studymate_user
      POSTGRES_PASSWORD: studymate_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
    networks:
      - dev-network

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.3
    container_name: studymate-weaviate-dev
    restart: unless-stopped
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8084'
      - --scheme
      - http
    ports:
      - "8084:8084"  # Weaviate vector database
      - "50051:50051"  # gRPC port
    volumes:
      - weaviate_dev_data:/var/lib/weaviate
    networks:
      - dev-network
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'

volumes:
  postgres_dev_data:
  weaviate_dev_data:

networks:
  dev-network:
    driver: bridge
    name: studymate-dev-network 