#!/bin/bash

# Default options
RECREATE=""
DETACH=""
BUILD=""

# Parse arguments
while getopts "rdb" opt; do
  case ${opt} in
    r )
      RECREATE="--force-recreate"
      ;;
    d )
      DETACH="-d"
      ;;
    b )
      BUILD="--build"
      ;;
    \? )
      echo "Usage: $0 [-r] [-d] [-b]"
      exit 1
      ;;
  esac
done

# Run docker compose with optional flags
docker compose -f docker-compose.dev.yml --env-file .env.dev up $BUILD $RECREATE $DETACH
