{{/*
PostgreSQL Secret - only create if not using existing secret
*/}}
{{- if and .Values.secrets.postgres.create (not .Values.secrets.postgres.existingSecret) }}
{{- if not .Values.secrets.postgres.data.password }}
{{- fail "ERROR: PostgreSQL password is required. Set via --set-string secrets.postgres.data.password=<value>" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres.name }}
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
type: Opaque
data:
  username: {{ .Values.secrets.postgres.data.username | b64enc }}
  password: {{ .Values.secrets.postgres.data.password | b64enc }}
---
{{- end }}

{{/*
Auth Secret - only create if not using existing secret
*/}}
{{- if and .Values.secrets.auth.create (not .Values.secrets.auth.existingSecret) }}
{{- if not .Values.secrets.auth.data.jwtSecret }}
{{- fail "ERROR: Auth JWT secret is required. Set via --set-string secrets.auth.data.jwtSecret=<value>" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.auth.name }}
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.auth.data.jwtSecret | b64enc }}
---
{{- end }}

{{/*
GenAI Secret - only create if not using existing secret
*/}}
{{- if and .Values.secrets.genai.create (not .Values.secrets.genai.existingSecret) }}
{{- if not .Values.secrets.genai.data.openWebUiApiKeyChat }}
{{- fail "ERROR: OpenWebUI Chat API key is required. Set via --set-string secrets.genai.data.openWebUiApiKeyChat=<value>" }}
{{- end }}
{{- if not .Values.secrets.genai.data.openWebUiApiKeyGen }}
{{- fail "ERROR: OpenWebUI Gen API key is required. Set via --set-string secrets.genai.data.openWebUiApiKeyGen=<value>" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.genai.name }}
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
type: Opaque
data:
  open-webui-api-key-chat: {{ .Values.secrets.genai.data.openWebUiApiKeyChat | b64enc }}
  open-webui-api-key-gen: {{ .Values.secrets.genai.data.openWebUiApiKeyGen | b64enc }}
  {{- if .Values.secrets.genai.data.langsmithApiKey }}
  langsmith-api-key: {{ .Values.secrets.genai.data.langsmithApiKey | b64enc }}
  {{- end }}
---
{{- end }}

 