# Document Service - Document management microservice
teamid: study-mate

# Secrets configuration
secrets:
  jwt:
    create: true
    existingSecret: false
    name: document-jwt-secret
    data:
      jwtSecret: ""  # Set via --set-string secrets.jwt.data.jwtSecret=<value>

documentService:
  image:
    repository: ghcr.io/aet-devops25/team-3/document-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8084
    targetPort: 8084
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker
    - name: SPRING_DATASOURCE_URL
      value: "jdbc:postgresql://study-mate-postgres:5432/study-mate"
    - name: SPRING_DATASOURCE_USERNAME
      value: "postgres"
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: study-mate-postgres
          key: password
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: auth-secret
          key: jwt-secret
    - name: AUTH_SERVICE_URL
      value: "http://study-mate-auth-service:8086"
    - name: GENAI_SERVICE_URL
      value: "http://study-mate-genai-service:8085"
    - name: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
      value: "50MB"
    - name: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
      value: "100MB"
