{{- if .Values.secrets.postgres.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres.name }}
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.postgres.data.username | b64enc }}
  password: {{ .Values.secrets.postgres.data.password | b64enc }}
---
{{- end }}
{{- if .Values.secrets.genai.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.genai.name }}
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.genai.data.apiKey | b64enc }}
---
{{- end }}
{{- if .Values.secrets.server.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.server.name }}
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.server.data.jwtSecret | b64enc }}
  database-url: {{ .Values.secrets.server.data.databaseUrl | b64enc }}
{{- end }} 