# Server Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "studymate.fullname" . }}-server
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "studymate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
---
# Client Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "studymate.fullname" . }}-client
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "studymate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client
---
# GenAI Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "studymate.fullname" . }}-genai
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai
spec:
  type: {{ .Values.genAi.service.type }}
  ports:
    - port: {{ .Values.genAi.service.port }}
      targetPort: {{ .Values.genAi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "studymate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: genai
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "studymate.fullname" . }}-postgres
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "studymate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
---
# Weaviate Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "studymate.fullname" . }}-weaviate
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: weaviate
spec:
  type: {{ .Values.weaviate.service.type }}
  ports:
    - port: {{ .Values.weaviate.service.port }}
      targetPort: {{ .Values.weaviate.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "studymate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: weaviate
---
# Auth Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "studymate.fullname" . }}-auth-service
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  type: {{ .Values.authService.service.type }}
  ports:
    - port: {{ .Values.authService.service.port }}
      targetPort: {{ .Values.authService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "studymate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
---
# Document Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "studymate.fullname" . }}-document-service
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: document-service
spec:
  type: {{ .Values.documentService.service.type }}
  ports:
    - port: {{ .Values.documentService.service.port }}
      targetPort: {{ .Values.documentService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "studymate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: document-service
---
# GenAI Microservice (Kotlin)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "studymate.fullname" . }}-genai-service
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai-service
spec:
  type: {{ .Values.genaiService.service.type }}
  ports:
    - port: {{ .Values.genaiService.service.port }}
      targetPort: {{ .Values.genaiService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "studymate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: genai-service 