apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "studymate.fullname" . }}-weaviate
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: weaviate
spec:
  replicas: {{ .Values.weaviate.replicaCount }}
  selector:
    matchLabels:
      {{- include "studymate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: weaviate
  template:
    metadata:
      labels:
        {{- include "studymate.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: weaviate
    spec:
      containers:
        - name: weaviate
          image: "{{ .Values.weaviate.image.repository }}:{{ .Values.weaviate.image.tag }}"
          imagePullPolicy: {{ .Values.weaviate.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: HTTP_PORT
              value: "8083"
            - name: GRPC_PORT
              value: "50051"
            {{- toYaml .Values.weaviate.env | nindent 12 }}
          volumeMounts:
            - name: weaviate-storage
              mountPath: /var/lib/weaviate
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: weaviate-storage
          persistentVolumeClaim:
            claimName: {{ include "studymate.fullname" . }}-weaviate-pvc 