apiVersion: v1
kind: Service
metadata:
  name: {{ include "studymate.fullname" . }}-genai-service
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai-service
spec:
  type: {{ .Values.genaiService.service.type }}
  ports:
    - port: {{ .Values.genaiService.service.port }}
      targetPort: {{ .Values.genaiService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "studymate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: genai-service 