apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
    spec:
      containers:
      - name: server
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.server.service.targetPort }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.server.env.SPRING_PROFILES_ACTIVE }}
        - name: SPRING_DATASOURCE_URL
          value: {{ .Values.server.env.SPRING_DATASOURCE_URL }}
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.server.env.SPRING_DATASOURCE_USERNAME }}
        - name: SPRING_DATASOURCE_PASSWORD
          value: {{ .Values.secrets.postgres.password }}
        resources:
          {{- toYaml .Values.server.resources | nindent 10 }}
