services:
  genai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genai-genai-dev
    restart: unless-stopped
    ports:
      - "8081:8081"  # FastAPI GenAI service
    environment:
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8083
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - weaviate
    volumes:
      - ./documents:/app/documents  # Mount documents for development

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.3
    container_name: genai-weaviate-dev
    restart: unless-stopped
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8083'
      - --scheme
      - http
    ports:
      - "8083:8083"  # Weaviate vector database
      - "50051:50051"  # gRPC port
    volumes:
      - weaviate_dev_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
  
volumes:
  postgres_dev_data:
  weaviate_dev_data: