from pydantic import BaseModel, Field

class FlashcardModel(BaseModel):
    question: str = Field(
        ...,
        description="The question to be answered"
    )
    answer: str = Field(
        ...,
        description="The answer to the question"
    )
    difficulty: str = Field(
        ...,
        description="The difficulty level of the flashcard (e.g., easy, medium, hard)"
    )   

class FlashcardResponse(BaseModel):
    flashcards: list[FlashcardModel] = Field(
        ...,
        description="A list of flashcards generated by the LLM"
    )