{{/*
GenAI Secret - only create if not using existing secret
*/}}
{{- if and .Values.secrets.genai.create (not .Values.secrets.genai.existingSecret) }}
{{- if not .Values.secrets.genai.data.openWebUiApiKeyChat }}
{{- fail "ERROR: OpenWebUI Chat API key is required. Set via --set-string secrets.genai.data.openWebUiApiKeyChat=<value>" }}
{{- end }}
{{- if not .Values.secrets.genai.data.openWebUiApiKeyGen }}
{{- fail "ERROR: OpenWebUI Gen API key is required. Set via --set-string secrets.genai.data.openWebUiApiKeyGen=<value>" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.genai.name }}
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
type: Opaque
data:
  open-webui-api-key-chat: {{ .Values.secrets.genai.data.openWebUiApiKeyChat | b64enc }}
  open-webui-api-key-gen: {{ .Values.secrets.genai.data.openWebUiApiKeyGen | b64enc }}
  {{- if .Values.secrets.genai.data.langsmithApiKey }}
  langsmith-api-key: {{ .Values.secrets.genai.data.langsmithApiKey | b64enc }}
  {{- end }}
{{- end }} 