apiVersion: v1
kind: Service
metadata:
  name: {{ include "weaviate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "weaviate.labels" . | nindent 4 }}
    app.kubernetes.io/component: weaviate
spec:
  type: {{ .Values.weaviate.service.type }}
  ports:
    - port: {{ .Values.weaviate.service.port }}
      targetPort: {{ .Values.weaviate.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.weaviate.service.grpcPort }}
      targetPort: {{ .Values.weaviate.service.grpcPort }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "weaviate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: weaviate 