# Persistence configuration
persistence:
  enabled: true
  size: 2Gi
  storageClass: ""  # Use default storage class

weaviate:
  image:
    repository: cr.weaviate.io/semitechnologies/weaviate
    tag: "1.30.3"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8087  
    targetPort: 8080
    grpcPort: 50051
  replicaCount: 1
  persistence:
    size: 10Gi
    storageClass: ""  # Use default storage class
  env:
    - name: QUERY_DEFAULTS_LIMIT
      value: "25"
    - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
      value: "true"
    - name: PERSISTENCE_DATA_PATH
      value: "/var/lib/weaviate"
    - name: ENABLE_API_BASED_MODULES
      value: "true"
    - name: CLUSTER_HOSTNAME
      value: "node1"
    - name: HTTP_PORT
      value: "8080"
    - name: GRPC_PORT
      value: "50051"