log:
  level: INFO

api:
  # Enable the API and dashboard for development
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: "0"
        graceTimeOut: "0"
      respondingTimeouts:
        readTimeout: "600s"
        writeTimeout: "600s"
        idleTimeout: "600s"

  websecure:
    address: ":443"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: "0"
        graceTimeOut: "0"
      respondingTimeouts:
        readTimeout: "600s"
        writeTimeout: "600s"
        idleTimeout: "600s"

certificatesResolvers:
  myresolver:
    acme:
      email: "wa.baroudi9@gmail.com"
      storage: "/letsencrypt/acme.json"
      tlsChallenge: {}
      # Uncomment the line below for testing/staging certificates to avoid rate limits
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"