# Default values for genai-service
replicaCount: 1

# GenAI Service - GenAI orchestration microservice (Kotlin)
teamid: study-mate

# Secrets configuration
secrets:
  jwt:
    create: true
    existingSecret: false
    name: genai-service-jwt-secret
    data:
      jwtSecret: ""  # Set via --set-string secrets.jwt.data.jwtSecret=<value>

genaiService:
  image:
    repository: ghcr.io/aet-devops25/team-3/genai-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8085
    targetPort: 8085
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: auth-secret
          key: jwt-secret
    - name: AUTH_SERVICE_URL
      value: "http://study-mate-auth-service:8086"
    - name: DOCUMENT_SERVICE_URL
      value: "http://study-mate-document-service:8084"
    - name: GENAI_BACKEND_URL
      value: "http://study-mate-genai:8081"
    - name: RATE_LIMIT_REQUESTS_PER_MINUTE
      value: "60"
    - name: SERVER_TOMCAT_THREADS_MAX
      value: "200"