global:
  scrape_interval: 15s

scrape_configs:
  # Microservices monitoring
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8083']
    metrics_path: /actuator/prometheus

  - job_name: 'document-service'
    static_configs:
      - targets: ['document-service:8084']
    metrics_path: /actuator/prometheus

  - job_name: 'genai-service'
    static_configs:
      - targets: ['genai-service:8085']
    metrics_path: /actuator/prometheus

  - job_name: 'genai'
    static_configs:
      - targets: ['genai:8081']

  # For dev only (when services are run manually)
  - job_name: 'genai-dev'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'server-dev'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: /actuator/prometheus