{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "studymate.fullname" . }}-prometheus-pvc
  namespace: {{ .Values.teamid }}
  labels:
    {{- include "studymate.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monitoring.prometheus.persistence.size }}
  {{- if .Values.monitoring.prometheus.persistence.storageClass }}
  storageClassName: {{ .Values.monitoring.prometheus.persistence.storageClass }}
  {{- end }}
{{- end }} 