name: Build StudyMate Images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      COMMIT_SHA: ${{ github.sha }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build client for EC2 deployment (studymate-tum.xyz)
      - name: Build and push client for EC2
        run: |
          docker build --platform linux/amd64 --build-arg VITE_API_BASE_URL=https://studymate-tum.xyz -t ghcr.io/aet-devops25/team-3/client:ec2-${COMMIT_SHA} ./client
          docker push ghcr.io/aet-devops25/team-3/client:ec2-${COMMIT_SHA}
          docker tag ghcr.io/aet-devops25/team-3/client:ec2-${COMMIT_SHA} ghcr.io/aet-devops25/team-3/client:ec2-latest
          docker push ghcr.io/aet-devops25/team-3/client:ec2-latest

      # Build client for Kubernetes deployment (study-mate.student.k8s.aet.cit.tum.de)
      - name: Build and push client for Kubernetes
        run: |
          docker build --platform linux/amd64 --build-arg VITE_API_BASE_URL=https://study-mate.student.k8s.aet.cit.tum.de -t ghcr.io/aet-devops25/team-3/client:k8s-${COMMIT_SHA} ./client
          docker push ghcr.io/aet-devops25/team-3/client:k8s-${COMMIT_SHA}
          docker tag ghcr.io/aet-devops25/team-3/client:k8s-${COMMIT_SHA} ghcr.io/aet-devops25/team-3/client:k8s-latest
          docker push ghcr.io/aet-devops25/team-3/client:k8s-latest

      # Build other microservices
      - name: Build and push auth-service
        run: |
          docker build --platform linux/amd64 -t ghcr.io/aet-devops25/team-3/auth-service:${COMMIT_SHA} ./server/auth-service
          docker push ghcr.io/aet-devops25/team-3/auth-service:${COMMIT_SHA}
          docker tag ghcr.io/aet-devops25/team-3/auth-service:${COMMIT_SHA} ghcr.io/aet-devops25/team-3/auth-service:latest
          docker push ghcr.io/aet-devops25/team-3/auth-service:latest
          docker tag ghcr.io/aet-devops25/team-3/auth-service:${COMMIT_SHA} ghcr.io/aet-devops25/team-3/auth-service:k8s-latest
          docker push ghcr.io/aet-devops25/team-3/auth-service:k8s-latest

      - name: Build and push document-service
        run: |
          docker build --platform linux/amd64 -t ghcr.io/aet-devops25/team-3/document-service:${COMMIT_SHA} ./server/document-service
          docker push ghcr.io/aet-devops25/team-3/document-service:${COMMIT_SHA}
          docker tag ghcr.io/aet-devops25/team-3/document-service:${COMMIT_SHA} ghcr.io/aet-devops25/team-3/document-service:latest
          docker push ghcr.io/aet-devops25/team-3/document-service:latest
          docker tag ghcr.io/aet-devops25/team-3/document-service:${COMMIT_SHA} ghcr.io/aet-devops25/team-3/document-service:k8s-latest
          docker push ghcr.io/aet-devops25/team-3/document-service:k8s-latest

      - name: Build and push genai-service
        run: |
          docker build --platform linux/amd64 -t ghcr.io/aet-devops25/team-3/genai-service:${COMMIT_SHA} ./server/genai-service
          docker push ghcr.io/aet-devops25/team-3/genai-service:${COMMIT_SHA}
          docker tag ghcr.io/aet-devops25/team-3/genai-service:${COMMIT_SHA} ghcr.io/aet-devops25/team-3/genai-service:latest
          docker push ghcr.io/aet-devops25/team-3/genai-service:latest
          docker tag ghcr.io/aet-devops25/team-3/genai-service:${COMMIT_SHA} ghcr.io/aet-devops25/team-3/genai-service:k8s-latest
          docker push ghcr.io/aet-devops25/team-3/genai-service:k8s-latest

      - name: Build and push eureka-server
        run: |
          docker build --platform linux/amd64 -t ghcr.io/aet-devops25/team-3/eureka-server:${COMMIT_SHA} ./server/eureka-server
          docker push ghcr.io/aet-devops25/team-3/eureka-server:${COMMIT_SHA}
          docker tag ghcr.io/aet-devops25/team-3/eureka-server:${COMMIT_SHA} ghcr.io/aet-devops25/team-3/eureka-server:latest
          docker push ghcr.io/aet-devops25/team-3/eureka-server:latest
          docker tag ghcr.io/aet-devops25/team-3/eureka-server:${COMMIT_SHA} ghcr.io/aet-devops25/team-3/eureka-server:k8s-latest
          docker push ghcr.io/aet-devops25/team-3/eureka-server:k8s-latest

      - name: Build and push genai
        run: |
          docker build --platform linux/amd64 -t ghcr.io/aet-devops25/team-3/genai:${COMMIT_SHA} ./genAi
          docker push ghcr.io/aet-devops25/team-3/genai:${COMMIT_SHA}
          docker tag ghcr.io/aet-devops25/team-3/genai:${COMMIT_SHA} ghcr.io/aet-devops25/team-3/genai:latest
          docker push ghcr.io/aet-devops25/team-3/genai:latest
          docker tag ghcr.io/aet-devops25/team-3/genai:${COMMIT_SHA} ghcr.io/aet-devops25/team-3/genai:k8s-latest
          docker push ghcr.io/aet-devops25/team-3/genai:k8s-latest 