name: Deploy StudyMate to Kubernetes

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
      domain:
        description: 'Domain name for deployment'
        required: true
        default: 'studymate.student.k8s.aet.cit.tum.de'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.0'

      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.POSTGRES_PASSWORD }}" ]; then
            echo "❌ POSTGRES_PASSWORD secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.JWT_SECRET }}" ]; then
            echo "❌ JWT_SECRET secret is not set"
            exit 1
          fi

          echo "✅ All required secrets are present"

      - name: Deploy to Kubernetes
        env:
          OPEN_WEBUI_API_KEY_CHAT: ${{ secrets.OPEN_WEBUI_API_KEY_CHAT }}
          OPEN_WEBUI_API_KEY_GEN: ${{ secrets.OPEN_WEBUI_API_KEY_GEN }}
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
        run: |
          chmod +x ./deploy-k8s.sh
          ./deploy-k8s.sh \
            --env ${{ github.event.inputs.environment || 'dev' }} \
            --domain ${{ github.event.inputs.domain || 'studymate.student.k8s.aet.cit.tum.de' }}

      - name: Verify deployment
        run: |
          echo "🔍 Checking deployment status..."
          kubectl get pods -n team-3 -l app.kubernetes.io/instance=studymate
          kubectl get services -n team-3 -l app.kubernetes.io/instance=studymate
          
          echo "🏥 Checking pod health..."
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/instance=studymate -n team-3 --timeout=300s

      - name: Get access information
        run: |
          echo "🌐 Access Information:"
          echo "Domain: ${{ github.event.inputs.domain || 'studymate.student.k8s.aet.cit.tum.de' }}"
          echo ""
          echo "🔗 Useful commands:"
          echo "kubectl get pods -n team-3"
          echo "kubectl logs -f deployment/studymate-client -n team-3"
          echo "kubectl port-forward svc/studymate-client 8080:80 -n team-3" 